-- OrangeNFe · Migration 007 — Tabela CFOP
CREATE TABLE IF NOT EXISTS cfop (
  codigo    text PRIMARY KEY,   -- ex: '5.102'
  descricao text NOT NULL,
  grupo     text NOT NULL,      -- '1.xxx – Entradas no Estado' etc
  tipo      text NOT NULL       -- '1' a '7'
);
ALTER TABLE cfop DISABLE ROW LEVEL SECURITY;
CREATE INDEX IF NOT EXISTS idx_cfop_tipo ON cfop(tipo);

INSERT INTO cfop (codigo, descricao, grupo, tipo) VALUES
  -- ─── GRUPO 1 – Entradas no Estado ───────────────────────────────
  ('1.102', 'Compra para comercialização', '1.xxx – Entradas no Estado', '1'),
  ('1.104', 'Compra para uso ou consumo', '1.xxx – Entradas no Estado', '1'),
  ('1.116', 'Compra para industrialização originada de encomenda para recebimento futuro', '1.xxx – Entradas no Estado', '1'),
  ('1.117', 'Compra para industrialização em operação com mercadoria sujeita ao regime de substituição tributária', '1.xxx – Entradas no Estado', '1'),
  ('1.118', 'Compra de mercadoria para comercialização pelo adquirente originada de encomenda para recebimento futuro', '1.xxx – Entradas no Estado', '1'),
  ('1.120', 'Compra para industrialização, em venda à ordem, já recebida do vendedor remetente', '1.xxx – Entradas no Estado', '1'),
  ('1.121', 'Compra para comercialização, em venda à ordem, já recebida do vendedor remetente', '1.xxx – Entradas no Estado', '1'),
  ('1.122', 'Compra para industrialização em operação com produto sujeito ao regime de substituição tributária', '1.xxx – Entradas no Estado', '1'),
  ('1.124', 'Industrialização efetuada por outra empresa', '1.xxx – Entradas no Estado', '1'),
  ('1.125', 'Industrialização efetuada por outra empresa quando a mercadoria remetida para utilização no processo de industrialização não transitou pelo estabelecimento adquirente', '1.xxx – Entradas no Estado', '1'),
  ('1.201', 'Devolução de venda de produção do estabelecimento', '1.xxx – Entradas no Estado', '1'),
  ('1.202', 'Devolução de venda de mercadoria adquirida ou recebida de terceiros', '1.xxx – Entradas no Estado', '1'),
  ('1.203', 'Devolução de venda de produção do estabelecimento, destinada à Zona Franca de Manaus ou Áreas de Livre Comércio', '1.xxx – Entradas no Estado', '1'),
  ('1.204', 'Devolução de venda de mercadoria adquirida ou recebida de terceiros, destinada à Zona Franca de Manaus ou Áreas de Livre Comércio', '1.xxx – Entradas no Estado', '1'),
  ('1.205', 'Anulação de valor relativo à prestação de serviço de comunicação', '1.xxx – Entradas no Estado', '1'),
  ('1.206', 'Anulação de valor relativo a prestação de serviço de transporte', '1.xxx – Entradas no Estado', '1'),
  ('1.207', 'Anulação de valor relativo à venda de energia elétrica', '1.xxx – Entradas no Estado', '1'),
  ('1.208', 'Devolução de produção do estabelecimento, remetida em transferência', '1.xxx – Entradas no Estado', '1'),
  ('1.209', 'Devolução de mercadoria adquirida ou recebida de terceiros, remetida em transferência', '1.xxx – Entradas no Estado', '1'),
  ('1.401', 'Compra para industrialização em operação com mercadoria sujeita ao regime de substituição tributária', '1.xxx – Entradas no Estado', '1'),
  ('1.403', 'Compra para comercialização em operação com mercadoria sujeita ao regime de substituição tributária', '1.xxx – Entradas no Estado', '1'),
  ('1.406', 'Compra de bem para o ativo imobilizado cuja mercadoria está sujeita ao regime de substituição tributária', '1.xxx – Entradas no Estado', '1'),
  ('1.407', 'Compra de mercadoria para uso ou consumo cuja mercadoria está sujeita ao regime de substituição tributária', '1.xxx – Entradas no Estado', '1'),
  ('1.408', 'Transferência para industrialização em operação com mercadoria sujeita ao regime de substituição tributária', '1.xxx – Entradas no Estado', '1'),
  ('1.409', 'Transferência para comercialização em operação com mercadoria sujeita ao regime de substituição tributária', '1.xxx – Entradas no Estado', '1'),
  ('1.501', 'Entrada de mercadoria recebida com fim específico de exportação', '1.xxx – Entradas no Estado', '1'),
  ('1.503', 'Entrada decorrente de devolução de produto remetido com fim específico de exportação, de produção do estabelecimento', '1.xxx – Entradas no Estado', '1'),
  ('1.504', 'Entrada decorrente de devolução de mercadoria remetida com fim específico de exportação, adquirida ou recebida de terceiros', '1.xxx – Entradas no Estado', '1'),
  ('1.551', 'Compra de bem para o ativo imobilizado', '1.xxx – Entradas no Estado', '1'),
  ('1.552', 'Transferência de bem do ativo imobilizado', '1.xxx – Entradas no Estado', '1'),
  ('1.553', 'Devolução de venda de bem do ativo imobilizado', '1.xxx – Entradas no Estado', '1'),
  ('1.555', 'Entrada de bem do ativo imobilizado de terceiro, remetido para uso no estabelecimento', '1.xxx – Entradas no Estado', '1'),
  ('1.556', 'Compra de material para uso ou consumo', '1.xxx – Entradas no Estado', '1'),
  ('1.557', 'Transferência de material para uso ou consumo', '1.xxx – Entradas no Estado', '1'),
  ('1.603', 'Ressarcimento de ICMS retido por substituição tributária', '1.xxx – Entradas no Estado', '1'),
  ('1.651', 'Compra de combustível ou lubrificante para industrialização subseqüente', '1.xxx – Entradas no Estado', '1'),
  ('1.652', 'Compra de combustível ou lubrificante para comercialização', '1.xxx – Entradas no Estado', '1'),
  ('1.653', 'Compra de combustível ou lubrificante por consumidor ou usuário final', '1.xxx – Entradas no Estado', '1'),
  ('1.658', 'Transferência de combustível e lubrificante adquirido para venda a varejo', '1.xxx – Entradas no Estado', '1'),
  ('1.901', 'Remessa para industrialização por encomenda', '1.xxx – Entradas no Estado', '1'),
  ('1.902', 'Retorno de mercadoria remetida para industrialização por encomenda', '1.xxx – Entradas no Estado', '1'),
  ('1.903', 'Retorno de mercadoria remetida para industrialização e não aplicada no referido processo', '1.xxx – Entradas no Estado', '1'),
  ('1.904', 'Retorno de remessa para venda fora do estabelecimento', '1.xxx – Entradas no Estado', '1'),
  ('1.905', 'Entrada de mercadoria recebida para depósito em depósito fechado ou armazém geral', '1.xxx – Entradas no Estado', '1'),
  ('1.906', 'Retorno de mercadoria remetida para depósito fechado ou armazém geral', '1.xxx – Entradas no Estado', '1'),
  ('1.907', 'Retorno simbólico de mercadoria remetida para depósito fechado ou armazém geral', '1.xxx – Entradas no Estado', '1'),
  ('1.908', 'Entrada de bem por conta de contrato de comodato', '1.xxx – Entradas no Estado', '1'),
  ('1.909', 'Retorno de bem remetido por conta de contrato de comodato', '1.xxx – Entradas no Estado', '1'),
  ('1.923', 'Entrada de mercadoria em poder de terceiros decorrente de acordo firmado anteriormente', '1.xxx – Entradas no Estado', '1'),
  ('1.933', 'Aquisição de serviços de comunicação por não contribuinte do ICMS', '1.xxx – Entradas no Estado', '1'),

  -- ─── GRUPO 2 – Entradas de Outros Estados ───────────────────────
  ('2.102', 'Compra para comercialização', '2.xxx – Entradas de Outros Estados', '2'),
  ('2.104', 'Compra para uso ou consumo', '2.xxx – Entradas de Outros Estados', '2'),
  ('2.116', 'Compra para industrialização originada de encomenda para recebimento futuro', '2.xxx – Entradas de Outros Estados', '2'),
  ('2.117', 'Compra para industrialização em operação com mercadoria sujeita ao regime de substituição tributária', '2.xxx – Entradas de Outros Estados', '2'),
  ('2.118', 'Compra de mercadoria para comercialização pelo adquirente originada de encomenda para recebimento futuro', '2.xxx – Entradas de Outros Estados', '2'),
  ('2.120', 'Compra para industrialização, em venda à ordem, já recebida do vendedor remetente', '2.xxx – Entradas de Outros Estados', '2'),
  ('2.121', 'Compra para comercialização, em venda à ordem, já recebida do vendedor remetente', '2.xxx – Entradas de Outros Estados', '2'),
  ('2.124', 'Industrialização efetuada por outra empresa', '2.xxx – Entradas de Outros Estados', '2'),
  ('2.201', 'Devolução de venda de produção do estabelecimento', '2.xxx – Entradas de Outros Estados', '2'),
  ('2.202', 'Devolução de venda de mercadoria adquirida ou recebida de terceiros', '2.xxx – Entradas de Outros Estados', '2'),
  ('2.401', 'Compra para industrialização em operação com mercadoria sujeita ao regime de substituição tributária', '2.xxx – Entradas de Outros Estados', '2'),
  ('2.403', 'Compra para comercialização em operação com mercadoria sujeita ao regime de substituição tributária', '2.xxx – Entradas de Outros Estados', '2'),
  ('2.551', 'Compra de bem para o ativo imobilizado', '2.xxx – Entradas de Outros Estados', '2'),
  ('2.552', 'Transferência de bem do ativo imobilizado', '2.xxx – Entradas de Outros Estados', '2'),
  ('2.556', 'Compra de material para uso ou consumo', '2.xxx – Entradas de Outros Estados', '2'),
  ('2.603', 'Ressarcimento de ICMS retido por substituição tributária', '2.xxx – Entradas de Outros Estados', '2'),
  ('2.651', 'Compra de combustível ou lubrificante para industrialização subseqüente', '2.xxx – Entradas de Outros Estados', '2'),
  ('2.652', 'Compra de combustível ou lubrificante para comercialização', '2.xxx – Entradas de Outros Estados', '2'),
  ('2.653', 'Compra de combustível ou lubrificante por consumidor ou usuário final', '2.xxx – Entradas de Outros Estados', '2'),
  ('2.904', 'Retorno de remessa para venda fora do estabelecimento', '2.xxx – Entradas de Outros Estados', '2'),
  ('2.906', 'Retorno de mercadoria remetida para depósito fechado ou armazém geral', '2.xxx – Entradas de Outros Estados', '2'),
  ('2.923', 'Entrada de mercadoria em poder de terceiros decorrente de acordo firmado anteriormente', '2.xxx – Entradas de Outros Estados', '2'),

  -- ─── GRUPO 3 – Entradas do Exterior ─────────────────────────────
  ('3.102', 'Compra para comercialização', '3.xxx – Entradas do Exterior', '3'),
  ('3.126', 'Compra para utilização na prestação de serviço sujeita ao ISSQN', '3.xxx – Entradas do Exterior', '3'),
  ('3.127', 'Compra para industrialização sob o regime de drawback', '3.xxx – Entradas do Exterior', '3'),
  ('3.201', 'Devolução de venda de produção do estabelecimento', '3.xxx – Entradas do Exterior', '3'),
  ('3.202', 'Devolução de venda de mercadoria adquirida ou recebida de terceiros', '3.xxx – Entradas do Exterior', '3'),
  ('3.205', 'Anulação de valor relativo à prestação de serviço de comunicação', '3.xxx – Entradas do Exterior', '3'),
  ('3.551', 'Compra de bem para o ativo imobilizado', '3.xxx – Entradas do Exterior', '3'),
  ('3.553', 'Devolução de venda de bem do ativo imobilizado', '3.xxx – Entradas do Exterior', '3'),
  ('3.556', 'Compra de material para uso ou consumo', '3.xxx – Entradas do Exterior', '3'),
  ('3.651', 'Compra de combustível ou lubrificante para industrialização subseqüente', '3.xxx – Entradas do Exterior', '3'),
  ('3.652', 'Compra de combustível ou lubrificante para comercialização', '3.xxx – Entradas do Exterior', '3'),
  ('3.653', 'Compra de combustível ou lubrificante por consumidor ou usuário final', '3.xxx – Entradas do Exterior', '3'),

  -- ─── GRUPO 5 – Saídas no Estado ─────────────────────────────────
  ('5.101', 'Venda de produção do estabelecimento', '5.xxx – Saídas no Estado', '5'),
  ('5.102', 'Venda de mercadoria adquirida ou recebida de terceiros', '5.xxx – Saídas no Estado', '5'),
  ('5.103', 'Venda de produção do estabelecimento, efetuada fora do estabelecimento', '5.xxx – Saídas no Estado', '5'),
  ('5.104', 'Venda de mercadoria adquirida ou recebida de terceiros, efetuada fora do estabelecimento', '5.xxx – Saídas no Estado', '5'),
  ('5.105', 'Venda de produção do estabelecimento que não deva por ela transitar', '5.xxx – Saídas no Estado', '5'),
  ('5.106', 'Venda de mercadoria adquirida ou recebida de terceiros, que não deva por ela transitar', '5.xxx – Saídas no Estado', '5'),
  ('5.109', 'Venda de produção do estabelecimento, destinada à Zona Franca de Manaus ou Áreas de Livre Comércio', '5.xxx – Saídas no Estado', '5'),
  ('5.110', 'Venda de mercadoria adquirida ou recebida de terceiros, destinada à Zona Franca de Manaus ou Áreas de Livre Comércio', '5.xxx – Saídas no Estado', '5'),
  ('5.111', 'Venda de produção do estabelecimento remetida anteriormente em consignação industrial', '5.xxx – Saídas no Estado', '5'),
  ('5.112', 'Venda de mercadoria adquirida ou recebida de terceiros remetida anteriormente em consignação industrial', '5.xxx – Saídas no Estado', '5'),
  ('5.113', 'Venda de produção do estabelecimento remetida anteriormente em consignação mercantil', '5.xxx – Saídas no Estado', '5'),
  ('5.114', 'Venda de mercadoria adquirida ou recebida de terceiros remetida anteriormente em consignação mercantil', '5.xxx – Saídas no Estado', '5'),
  ('5.115', 'Venda de mercadoria adquirida ou recebida de terceiros, recebida anteriormente em consignação mercantil', '5.xxx – Saídas no Estado', '5'),
  ('5.116', 'Venda de produção do estabelecimento originada de encomenda para entrega futura', '5.xxx – Saídas no Estado', '5'),
  ('5.117', 'Venda de mercadoria adquirida ou recebida de terceiros, originada de encomenda para entrega futura', '5.xxx – Saídas no Estado', '5'),
  ('5.120', 'Venda de produção do estabelecimento, com fornecimento de alimentação e bebidas', '5.xxx – Saídas no Estado', '5'),
  ('5.122', 'Venda de produção do estabelecimento remetida para industrialização, por conta e ordem do adquirente', '5.xxx – Saídas no Estado', '5'),
  ('5.124', 'Industrialização efetuada para outra empresa', '5.xxx – Saídas no Estado', '5'),
  ('5.125', 'Industrialização efetuada para outra empresa quando a mercadoria recebida para utilização no processo de industrialização não transitou pelo estabelecimento adquirente-remitente', '5.xxx – Saídas no Estado', '5'),
  ('5.151', 'Transferência de produção do estabelecimento', '5.xxx – Saídas no Estado', '5'),
  ('5.152', 'Transferência de mercadoria adquirida ou recebida de terceiros', '5.xxx – Saídas no Estado', '5'),
  ('5.153', 'Transferência de energia elétrica', '5.xxx – Saídas no Estado', '5'),
  ('5.155', 'Transferência de produção do estabelecimento, que não deva por ela transitar', '5.xxx – Saídas no Estado', '5'),
  ('5.156', 'Transferência de mercadoria adquirida ou recebida de terceiros, que não deva por ela transitar', '5.xxx – Saídas no Estado', '5'),
  ('5.201', 'Devolução de compra para industrialização', '5.xxx – Saídas no Estado', '5'),
  ('5.202', 'Devolução de compra para comercialização', '5.xxx – Saídas no Estado', '5'),
  ('5.204', 'Devolução de compra para uso ou consumo', '5.xxx – Saídas no Estado', '5'),
  ('5.205', 'Anulação de valor relativo à aquisição de serviço de comunicação', '5.xxx – Saídas no Estado', '5'),
  ('5.206', 'Anulação de valor relativo à aquisição de serviço de transporte', '5.xxx – Saídas no Estado', '5'),
  ('5.207', 'Anulação de valor relativo à compra de energia elétrica', '5.xxx – Saídas no Estado', '5'),
  ('5.208', 'Devolução de mercadoria recebida em transferência para industrialização', '5.xxx – Saídas no Estado', '5'),
  ('5.209', 'Devolução de mercadoria recebida em transferência para comercialização', '5.xxx – Saídas no Estado', '5'),
  ('5.210', 'Devolução de compra para utilização na prestação de serviço', '5.xxx – Saídas no Estado', '5'),
  ('5.211', 'Devolução de compras para industrialização em operação com mercadoria sujeita ao regime de substituição tributária', '5.xxx – Saídas no Estado', '5'),
  ('5.212', 'Devolução de compras para comercialização em operação com mercadoria sujeita ao regime de substituição tributária', '5.xxx – Saídas no Estado', '5'),
  ('5.213', 'Devolução de entrada de mercadoria com previsão de posterior ajuste ou fixação de preço, em operação com mercadoria sujeita ao regime de substituição tributária', '5.xxx – Saídas no Estado', '5'),
  ('5.214', 'Devolução de compra para uso ou consumo em operação com mercadoria sujeita ao regime de substituição tributária', '5.xxx – Saídas no Estado', '5'),
  ('5.301', 'Venda de produção do estabelecimento', '5.xxx – Saídas no Estado', '5'),
  ('5.302', 'Venda de mercadoria adquirida ou recebida de terceiros', '5.xxx – Saídas no Estado', '5'),
  ('5.303', 'Venda de produção do estabelecimento, efetuada fora do estabelecimento', '5.xxx – Saídas no Estado', '5'),
  ('5.304', 'Venda de mercadoria adquirida ou recebida de terceiros, efetuada fora do estabelecimento', '5.xxx – Saídas no Estado', '5'),
  ('5.351', 'Venda de produção do estabelecimento', '5.xxx – Saídas no Estado', '5'),
  ('5.352', 'Venda de mercadoria adquirida ou recebida de terceiros', '5.xxx – Saídas no Estado', '5'),
  ('5.353', 'Venda de produção do estabelecimento, efetuada fora do estabelecimento', '5.xxx – Saídas no Estado', '5'),
  ('5.354', 'Venda de mercadoria adquirida ou recebida de terceiros, efetuada fora do estabelecimento', '5.xxx – Saídas no Estado', '5'),
  ('5.401', 'Venda de produção do estabelecimento em operação com produto sujeito ao regime de substituição tributária, na condição de contribuinte substituto', '5.xxx – Saídas no Estado', '5'),
  ('5.403', 'Venda de mercadoria adquirida ou recebida de terceiros em operação com mercadoria sujeita ao regime de substituição tributária, na condição de contribuinte substituto', '5.xxx – Saídas no Estado', '5'),
  ('5.405', 'Venda de mercadoria adquirida ou recebida de terceiros, sujeita ao regime de substituição tributária, na condição de contribuinte-substituído', '5.xxx – Saídas no Estado', '5'),
  ('5.408', 'Transferência de produção do estabelecimento em operação com produto sujeito ao regime de substituição tributária', '5.xxx – Saídas no Estado', '5'),
  ('5.409', 'Transferência de mercadoria adquirida ou recebida de terceiros em operação com mercadoria sujeita ao regime de substituição tributária', '5.xxx – Saídas no Estado', '5'),
  ('5.410', 'Devolução de compra para industrialização em operação com mercadoria sujeita ao regime de substituição tributária', '5.xxx – Saídas no Estado', '5'),
  ('5.501', 'Remessa de produção do estabelecimento, com fim específico de exportação', '5.xxx – Saídas no Estado', '5'),
  ('5.502', 'Remessa de mercadoria adquirida ou recebida de terceiros, com fim específico de exportação', '5.xxx – Saídas no Estado', '5'),
  ('5.503', 'Devolução de mercadoria recebida com fim específico de exportação', '5.xxx – Saídas no Estado', '5'),
  ('5.504', 'Remessa de mercadorias para formação de lote de exportação, de produtos industrializados ou produzidos pelo próprio estabelecimento', '5.xxx – Saídas no Estado', '5'),
  ('5.505', 'Remessa de mercadorias, adquiridas ou recebidas de terceiros, para formação de lote de exportação', '5.xxx – Saídas no Estado', '5'),
  ('5.551', 'Venda de bem do ativo imobilizado', '5.xxx – Saídas no Estado', '5'),
  ('5.552', 'Transferência de bem do ativo imobilizado', '5.xxx – Saídas no Estado', '5'),
  ('5.553', 'Devolução de compra de bem para o ativo imobilizado', '5.xxx – Saídas no Estado', '5'),
  ('5.554', 'Remessa de bem do ativo imobilizado para uso fora do estabelecimento', '5.xxx – Saídas no Estado', '5'),
  ('5.555', 'Devolução de bem do ativo imobilizado de terceiro, recebido para uso no estabelecimento', '5.xxx – Saídas no Estado', '5'),
  ('5.556', 'Venda de material de uso ou consumo', '5.xxx – Saídas no Estado', '5'),
  ('5.557', 'Transferência de material de uso ou consumo', '5.xxx – Saídas no Estado', '5'),
  ('5.601', 'Transferência de crédito de ICMS acumulado', '5.xxx – Saídas no Estado', '5'),
  ('5.602', 'Transferência de saldo credor de ICMS para outro estabelecimento da mesma empresa, destinado à compensação de saldo devedor de ICMS', '5.xxx – Saídas no Estado', '5'),
  ('5.603', 'Ressarcimento de ICMS retido por substituição tributária', '5.xxx – Saídas no Estado', '5'),
  ('5.605', 'Transferência de saldo devedor de ICMS de outro estabelecimento da mesma empresa', '5.xxx – Saídas no Estado', '5'),
  ('5.606', 'Utilização de saldo credor de ICMS para extinção por compensação de débitos fiscais', '5.xxx – Saídas no Estado', '5'),
  ('5.651', 'Venda de combustível ou lubrificante de produção do estabelecimento destinados à industrialização subseqüente', '5.xxx – Saídas no Estado', '5'),
  ('5.652', 'Venda de combustível ou lubrificante de produção do estabelecimento destinados à comercialização', '5.xxx – Saídas no Estado', '5'),
  ('5.653', 'Venda de combustível ou lubrificante de produção do estabelecimento destinados a consumidor ou usuário final', '5.xxx – Saídas no Estado', '5'),
  ('5.655', 'Venda de combustível ou lubrificante adquiridos ou recebidos de terceiros destinados a consumidor ou usuário final', '5.xxx – Saídas no Estado', '5'),
  ('5.656', 'Venda de combustível ou lubrificante adquiridos ou recebidos de terceiros destinados a consumidor ou usuário final', '5.xxx – Saídas no Estado', '5'),
  ('5.657', 'Remessa de combustível ou lubrificante adquiridos ou recebidos de terceiros para venda fora do estabelecimento', '5.xxx – Saídas no Estado', '5'),
  ('5.658', 'Transferência de combustível ou lubrificante adquiridos ou recebidos de terceiros', '5.xxx – Saídas no Estado', '5'),
  ('5.901', 'Remessa para industrialização por encomenda', '5.xxx – Saídas no Estado', '5'),
  ('5.902', 'Retorno de mercadoria utilizada na industrialização por encomenda', '5.xxx – Saídas no Estado', '5'),
  ('5.903', 'Retorno de mercadoria recebida para industrialização e não aplicada no referido processo', '5.xxx – Saídas no Estado', '5'),
  ('5.904', 'Remessa para venda fora do estabelecimento', '5.xxx – Saídas no Estado', '5'),
  ('5.905', 'Remessa para depósito fechado ou armazém geral', '5.xxx – Saídas no Estado', '5'),
  ('5.906', 'Retorno de mercadoria depositada em depósito fechado ou armazém geral', '5.xxx – Saídas no Estado', '5'),
  ('5.907', 'Retorno simbólico de mercadoria depositada em depósito fechado ou armazém geral', '5.xxx – Saídas no Estado', '5'),
  ('5.908', 'Remessa de bem por conta de contrato de comodato', '5.xxx – Saídas no Estado', '5'),
  ('5.909', 'Retorno de bem remetido por conta de contrato de comodato', '5.xxx – Saídas no Estado', '5'),
  ('5.910', 'Remessa em bonificação, doação ou brinde', '5.xxx – Saídas no Estado', '5'),
  ('5.911', 'Remessa de amostra grátis', '5.xxx – Saídas no Estado', '5'),
  ('5.912', 'Remessa de mercadoria ou bem para demonstração', '5.xxx – Saídas no Estado', '5'),
  ('5.913', 'Retorno de mercadoria ou bem recebido para demonstração', '5.xxx – Saídas no Estado', '5'),
  ('5.914', 'Remessa de mercadoria ou bem para exposição ou feira', '5.xxx – Saídas no Estado', '5'),
  ('5.915', 'Remessa de mercadoria ou bem para conserto ou reparo', '5.xxx – Saídas no Estado', '5'),
  ('5.916', 'Retorno de mercadoria ou bem recebido para conserto ou reparo', '5.xxx – Saídas no Estado', '5'),
  ('5.917', 'Remessa de mercadoria em consignação mercantil ou industrial', '5.xxx – Saídas no Estado', '5'),
  ('5.918', 'Devolução de mercadoria recebida em consignação mercantil ou industrial', '5.xxx – Saídas no Estado', '5'),
  ('5.919', 'Devolução simbólica de mercadoria vendida ou utilizada em processo industrial, recebida anteriormente em consignação mercantil ou industrial', '5.xxx – Saídas no Estado', '5'),
  ('5.920', 'Remessa de vasilhame ou sacaria', '5.xxx – Saídas no Estado', '5'),
  ('5.921', 'Devolução de vasilhame ou sacaria', '5.xxx – Saídas no Estado', '5'),
  ('5.922', 'Lançamento efetuado a título de simples faturamento decorrente de venda para entrega futura', '5.xxx – Saídas no Estado', '5'),
  ('5.923', 'Remessa de mercadoria por conta e ordem de terceiros, em venda à ordem ou em operações com armazém geral ou depósito fechado', '5.xxx – Saídas no Estado', '5'),
  ('5.924', 'Remessa para industrialização por conta e ordem do adquirente da mercadoria, quando esta não transitar pelo estabelecimento do adquirente', '5.xxx – Saídas no Estado', '5'),
  ('5.925', 'Retorno de mercadoria remetida para industrialização por conta e ordem do adquirente da mercadoria, quando esta não transitou pelo estabelecimento do adquirente', '5.xxx – Saídas no Estado', '5'),
  ('5.926', 'Lançamento efetuado a título de reclassificação de mercadoria decorrente de formação de kit ou de sua desagregação', '5.xxx – Saídas no Estado', '5'),
  ('5.927', 'Lançamento efetuado a título de baixa de estoque decorrente de perda, roubo ou deterioração', '5.xxx – Saídas no Estado', '5'),
  ('5.928', 'Lançamento efetuado a título de baixa de estoque decorrente do encerramento da atividade da empresa', '5.xxx – Saídas no Estado', '5'),
  ('5.929', 'Lançamento efetuado em decorrência de emissão de documento fiscal relativo a operação ou prestação também acobertada por documento fiscal emitido por outra empresa', '5.xxx – Saídas no Estado', '5'),
  ('5.931', 'Lançamento efetuado em decorrência da responsabilidade de retenção do imposto por substituição tributária, atribuída ao remetente ou alienante da mercadoria, pelo serviço de transporte realizado por transportador autônomo ou por empresa transportadora de outra UF, não inscrita no cadastro de contribuintes da UF onde iniciado o serviço', '5.xxx – Saídas no Estado', '5'),
  ('5.932', 'Prestação de serviço de transporte iniciada em UF diversa daquela onde inscrito o prestador', '5.xxx – Saídas no Estado', '5'),
  ('5.933', 'Prestação de serviço tributado pelo ISSQN', '5.xxx – Saídas no Estado', '5'),
  ('5.934', 'Remessa simbólica de mercadoria depositada em armazém geral ou depósito fechado', '5.xxx – Saídas no Estado', '5'),
  ('5.949', 'Outra saída de mercadoria ou prestação de serviço não especificado', '5.xxx – Saídas no Estado', '5'),

  -- ─── GRUPO 6 – Saídas para Outros Estados ───────────────────────
  ('6.101', 'Venda de produção do estabelecimento', '6.xxx – Saídas para Outros Estados', '6'),
  ('6.102', 'Venda de mercadoria adquirida ou recebida de terceiros', '6.xxx – Saídas para Outros Estados', '6'),
  ('6.103', 'Venda de produção do estabelecimento, efetuada fora do estabelecimento', '6.xxx – Saídas para Outros Estados', '6'),
  ('6.104', 'Venda de mercadoria adquirida ou recebida de terceiros, efetuada fora do estabelecimento', '6.xxx – Saídas para Outros Estados', '6'),
  ('6.105', 'Venda de produção do estabelecimento que não deva por ela transitar', '6.xxx – Saídas para Outros Estados', '6'),
  ('6.106', 'Venda de mercadoria adquirida ou recebida de terceiros, que não deva por ela transitar', '6.xxx – Saídas para Outros Estados', '6'),
  ('6.107', 'Venda de produção do estabelecimento, destinada a não contribuinte', '6.xxx – Saídas para Outros Estados', '6'),
  ('6.108', 'Venda de mercadoria adquirida ou recebida de terceiros, destinada a não contribuinte', '6.xxx – Saídas para Outros Estados', '6'),
  ('6.109', 'Venda de produção do estabelecimento, destinada à Zona Franca de Manaus ou Áreas de Livre Comércio', '6.xxx – Saídas para Outros Estados', '6'),
  ('6.110', 'Venda de mercadoria adquirida ou recebida de terceiros, destinada à Zona Franca de Manaus ou Áreas de Livre Comércio', '6.xxx – Saídas para Outros Estados', '6'),
  ('6.116', 'Venda de produção do estabelecimento originada de encomenda para entrega futura', '6.xxx – Saídas para Outros Estados', '6'),
  ('6.117', 'Venda de mercadoria adquirida ou recebida de terceiros, originada de encomenda para entrega futura', '6.xxx – Saídas para Outros Estados', '6'),
  ('6.120', 'Venda de produção do estabelecimento, com fornecimento de alimentação e bebidas', '6.xxx – Saídas para Outros Estados', '6'),
  ('6.122', 'Venda de produção do estabelecimento remetida para industrialização, por conta e ordem do adquirente', '6.xxx – Saídas para Outros Estados', '6'),
  ('6.123', 'Industrialização efetuada para outra empresa', '6.xxx – Saídas para Outros Estados', '6'),
  ('6.124', 'Industrialização efetuada para outra empresa quando a mercadoria recebida para utilização no processo de industrialização não transitou pelo estabelecimento adquirente-remitente', '6.xxx – Saídas para Outros Estados', '6'),
  ('6.151', 'Transferência de produção do estabelecimento', '6.xxx – Saídas para Outros Estados', '6'),
  ('6.152', 'Transferência de mercadoria adquirida ou recebida de terceiros', '6.xxx – Saídas para Outros Estados', '6'),
  ('6.153', 'Transferência de energia elétrica', '6.xxx – Saídas para Outros Estados', '6'),
  ('6.201', 'Devolução de compra para industrialização', '6.xxx – Saídas para Outros Estados', '6'),
  ('6.202', 'Devolução de compra para comercialização', '6.xxx – Saídas para Outros Estados', '6'),
  ('6.205', 'Anulação de valor relativo à aquisição de serviço de comunicação', '6.xxx – Saídas para Outros Estados', '6'),
  ('6.206', 'Anulação de valor relativo à aquisição de serviço de transporte', '6.xxx – Saídas para Outros Estados', '6'),
  ('6.207', 'Anulação de valor relativo à compra de energia elétrica', '6.xxx – Saídas para Outros Estados', '6'),
  ('6.208', 'Devolução de mercadoria recebida em transferência para industrialização', '6.xxx – Saídas para Outros Estados', '6'),
  ('6.209', 'Devolução de mercadoria recebida em transferência para comercialização', '6.xxx – Saídas para Outros Estados', '6'),
  ('6.210', 'Devolução de compra para utilização na prestação de serviço', '6.xxx – Saídas para Outros Estados', '6'),
  ('6.301', 'Venda de produção do estabelecimento', '6.xxx – Saídas para Outros Estados', '6'),
  ('6.302', 'Venda de mercadoria adquirida ou recebida de terceiros', '6.xxx – Saídas para Outros Estados', '6'),
  ('6.351', 'Venda de produção do estabelecimento', '6.xxx – Saídas para Outros Estados', '6'),
  ('6.352', 'Venda de mercadoria adquirida ou recebida de terceiros', '6.xxx – Saídas para Outros Estados', '6'),
  ('6.401', 'Venda de produção do estabelecimento em operação com produto sujeito ao regime de substituição tributária, na condição de contribuinte substituto', '6.xxx – Saídas para Outros Estados', '6'),
  ('6.403', 'Venda de mercadoria adquirida ou recebida de terceiros em operação com mercadoria sujeita ao regime de substituição tributária, na condição de contribuinte substituto', '6.xxx – Saídas para Outros Estados', '6'),
  ('6.404', 'Venda de mercadoria sujeita ao regime de substituição tributária, cujo imposto já tenha sido retido anteriormente', '6.xxx – Saídas para Outros Estados', '6'),
  ('6.408', 'Transferência de produção do estabelecimento em operação com produto sujeito ao regime de substituição tributária', '6.xxx – Saídas para Outros Estados', '6'),
  ('6.409', 'Transferência de mercadoria adquirida ou recebida de terceiros em operação com mercadoria sujeita ao regime de substituição tributária', '6.xxx – Saídas para Outros Estados', '6'),
  ('6.501', 'Remessa de produção do estabelecimento, com fim específico de exportação', '6.xxx – Saídas para Outros Estados', '6'),
  ('6.502', 'Remessa de mercadoria adquirida ou recebida de terceiros, com fim específico de exportação', '6.xxx – Saídas para Outros Estados', '6'),
  ('6.503', 'Devolução de mercadoria recebida com fim específico de exportação', '6.xxx – Saídas para Outros Estados', '6'),
  ('6.551', 'Venda de bem do ativo imobilizado', '6.xxx – Saídas para Outros Estados', '6'),
  ('6.552', 'Transferência de bem do ativo imobilizado', '6.xxx – Saídas para Outros Estados', '6'),
  ('6.553', 'Devolução de compra de bem para o ativo imobilizado', '6.xxx – Saídas para Outros Estados', '6'),
  ('6.554', 'Remessa de bem do ativo imobilizado para uso fora do estabelecimento', '6.xxx – Saídas para Outros Estados', '6'),
  ('6.555', 'Devolução de bem do ativo imobilizado de terceiro, recebido para uso no estabelecimento', '6.xxx – Saídas para Outros Estados', '6'),
  ('6.556', 'Venda de material de uso ou consumo', '6.xxx – Saídas para Outros Estados', '6'),
  ('6.557', 'Transferência de material de uso ou consumo', '6.xxx – Saídas para Outros Estados', '6'),
  ('6.603', 'Ressarcimento de ICMS retido por substituição tributária', '6.xxx – Saídas para Outros Estados', '6'),
  ('6.651', 'Venda de combustível ou lubrificante de produção do estabelecimento destinados à industrialização subseqüente', '6.xxx – Saídas para Outros Estados', '6'),
  ('6.653', 'Venda de combustível ou lubrificante de produção do estabelecimento destinados a consumidor ou usuário final', '6.xxx – Saídas para Outros Estados', '6'),
  ('6.656', 'Venda de combustível ou lubrificante adquiridos ou recebidos de terceiros destinados a consumidor ou usuário final', '6.xxx – Saídas para Outros Estados', '6'),
  ('6.657', 'Remessa de combustível ou lubrificante adquiridos ou recebidos de terceiros para venda fora do estabelecimento', '6.xxx – Saídas para Outros Estados', '6'),
  ('6.658', 'Transferência de combustível ou lubrificante adquiridos ou recebidos de terceiros', '6.xxx – Saídas para Outros Estados', '6'),
  ('6.901', 'Remessa para industrialização por encomenda', '6.xxx – Saídas para Outros Estados', '6'),
  ('6.902', 'Retorno de mercadoria utilizada na industrialização por encomenda', '6.xxx – Saídas para Outros Estados', '6'),
  ('6.903', 'Retorno de mercadoria recebida para industrialização e não aplicada no referido processo', '6.xxx – Saídas para Outros Estados', '6'),
  ('6.904', 'Remessa para venda fora do estabelecimento', '6.xxx – Saídas para Outros Estados', '6'),
  ('6.905', 'Remessa para depósito fechado ou armazém geral', '6.xxx – Saídas para Outros Estados', '6'),
  ('6.906', 'Retorno de mercadoria depositada em depósito fechado ou armazém geral', '6.xxx – Saídas para Outros Estados', '6'),
  ('6.907', 'Retorno simbólico de mercadoria depositada em depósito fechado ou armazém geral', '6.xxx – Saídas para Outros Estados', '6'),
  ('6.908', 'Remessa de bem por conta de contrato de comodato', '6.xxx – Saídas para Outros Estados', '6'),
  ('6.909', 'Retorno de bem remetido por conta de contrato de comodato', '6.xxx – Saídas para Outros Estados', '6'),
  ('6.910', 'Remessa em bonificação, doação ou brinde', '6.xxx – Saídas para Outros Estados', '6'),
  ('6.911', 'Remessa de amostra grátis', '6.xxx – Saídas para Outros Estados', '6'),
  ('6.912', 'Remessa de mercadoria ou bem para demonstração', '6.xxx – Saídas para Outros Estados', '6'),
  ('6.913', 'Retorno de mercadoria ou bem recebido para demonstração', '6.xxx – Saídas para Outros Estados', '6'),
  ('6.914', 'Remessa de mercadoria ou bem para exposição ou feira', '6.xxx – Saídas para Outros Estados', '6'),
  ('6.915', 'Remessa de mercadoria ou bem para conserto ou reparo', '6.xxx – Saídas para Outros Estados', '6'),
  ('6.916', 'Retorno de mercadoria ou bem recebido para conserto ou reparo', '6.xxx – Saídas para Outros Estados', '6'),
  ('6.917', 'Remessa de mercadoria em consignação mercantil ou industrial', '6.xxx – Saídas para Outros Estados', '6'),
  ('6.918', 'Devolução de mercadoria recebida em consignação mercantil ou industrial', '6.xxx – Saídas para Outros Estados', '6'),
  ('6.919', 'Devolução simbólica de mercadoria vendida ou utilizada em processo industrial, recebida anteriormente em consignação mercantil ou industrial', '6.xxx – Saídas para Outros Estados', '6'),
  ('6.920', 'Remessa de vasilhame ou sacaria', '6.xxx – Saídas para Outros Estados', '6'),
  ('6.921', 'Devolução de vasilhame ou sacaria', '6.xxx – Saídas para Outros Estados', '6'),
  ('6.922', 'Lançamento efetuado a título de simples faturamento decorrente de venda para entrega futura', '6.xxx – Saídas para Outros Estados', '6'),
  ('6.923', 'Remessa de mercadoria por conta e ordem de terceiros, em venda à ordem ou em operações com armazém geral ou depósito fechado', '6.xxx – Saídas para Outros Estados', '6'),
  ('6.924', 'Remessa para industrialização por conta e ordem do adquirente da mercadoria, quando esta não transitar pelo estabelecimento do adquirente', '6.xxx – Saídas para Outros Estados', '6'),
  ('6.925', 'Retorno de mercadoria remetida para industrialização por conta e ordem do adquirente da mercadoria, quando esta não transitou pelo estabelecimento do adquirente', '6.xxx – Saídas para Outros Estados', '6'),
  ('6.929', 'Lançamento efetuado em decorrência de emissão de documento fiscal relativo a operação ou prestação também acobertada por documento fiscal emitido por outra empresa', '6.xxx – Saídas para Outros Estados', '6'),
  ('6.933', 'Prestação de serviço tributado pelo ISSQN', '6.xxx – Saídas para Outros Estados', '6'),
  ('6.949', 'Outra saída de mercadoria ou prestação de serviço não especificado', '6.xxx – Saídas para Outros Estados', '6'),

  -- ─── GRUPO 7 – Saídas para o Exterior ───────────────────────────
  ('7.101', 'Venda de produção do estabelecimento', '7.xxx – Saídas para o Exterior', '7'),
  ('7.102', 'Venda de mercadoria adquirida ou recebida de terceiros', '7.xxx – Saídas para o Exterior', '7'),
  ('7.105', 'Venda de produção do estabelecimento, que não deva por ela transitar', '7.xxx – Saídas para o Exterior', '7'),
  ('7.106', 'Venda de mercadoria adquirida ou recebida de terceiros, que não deva por ela transitar', '7.xxx – Saídas para o Exterior', '7'),
  ('7.127', 'Venda de produção do estabelecimento sob o regime de drawback', '7.xxx – Saídas para o Exterior', '7'),
  ('7.201', 'Devolução de compra para industrialização', '7.xxx – Saídas para o Exterior', '7'),
  ('7.202', 'Devolução de compra para comercialização', '7.xxx – Saídas para o Exterior', '7'),
  ('7.210', 'Devolução de compra para utilização na prestação de serviço', '7.xxx – Saídas para o Exterior', '7'),
  ('7.211', 'Devolução de compras para industrialização sob o regime de drawback', '7.xxx – Saídas para o Exterior', '7'),
  ('7.501', 'Exportação de mercadorias recebidas com fim específico de exportação', '7.xxx – Saídas para o Exterior', '7'),
  ('7.504', 'Exportação de mercadorias recebidas com fim específico de exportação', '7.xxx – Saídas para o Exterior', '7'),
  ('7.551', 'Venda de bem do ativo imobilizado', '7.xxx – Saídas para o Exterior', '7'),
  ('7.553', 'Devolução de compra de bem para o ativo imobilizado', '7.xxx – Saídas para o Exterior', '7'),
  ('7.556', 'Venda de material de uso ou consumo', '7.xxx – Saídas para o Exterior', '7'),
  ('7.601', 'Exportação de combustíveis de produção do estabelecimento', '7.xxx – Saídas para o Exterior', '7'),
  ('7.651', 'Exportação de combustível ou lubrificante de produção do estabelecimento', '7.xxx – Saídas para o Exterior', '7'),
  ('7.930', 'Lançamento efetuado a título de devolução de bem do ativo imobilizado, em operações com o exterior', '7.xxx – Saídas para o Exterior', '7'),
  ('7.949', 'Outra saída de mercadoria ou prestação de serviço não especificado', '7.xxx – Saídas para o Exterior', '7')
ON CONFLICT (codigo) DO NOTHING;

-- Total: 291 registros inseridos
