-- OrangeNFe · Migration 008 — Tabela Países
-- Fonte: Banco Central do Brasil (BCB) / ISO Alpha-2
-- 142 países com códigos BACEN únicos (corrigidos em 2026-05-27)
CREATE TABLE IF NOT EXISTS paises (
  bacen      text PRIMARY KEY,  -- código BACEN 4 dígitos, ex: '1058'
  iso        text NOT NULL,     -- ISO Alpha-2, ex: 'BR'
  nome       text NOT NULL,
  continente text NOT NULL
);
ALTER TABLE paises DISABLE ROW LEVEL SECURITY;
CREATE INDEX IF NOT EXISTS idx_paises_continente ON paises(continente);

INSERT INTO paises (bacen, iso, nome, continente) VALUES
  -- ─── América do Sul ──────────────────────────────
  ('1058', 'BR', 'Brasil',           'América'),
  ('0531', 'AR', 'Argentina',        'América'),
  ('0973', 'BO', 'Bolívia',          'América'),
  ('1715', 'CL', 'Chile',            'América'),
  ('1830', 'CO', 'Colômbia',         'América'),
  ('2078', 'EC', 'Equador',          'América'),
  ('5118', 'PY', 'Paraguai',         'América'),
  ('5231', 'PE', 'Peru',             'América'),
  ('7080', 'UY', 'Uruguai',          'América'),
  ('7137', 'VE', 'Venezuela',        'América'),
  ('6300', 'SR', 'Suriname',         'América'),
  ('3301', 'GY', 'Guiana',           'América'),
  ('1541', 'GF', 'Guiana Francesa',  'América'),

  -- ─── América do Norte e Central / Caribe ─────────
  ('1491', 'CA', 'Canadá',           'América'),
  ('2496', 'US', 'Estados Unidos',   'América'),
  ('4200', 'MX', 'México',           'América'),
  ('1571', 'CR', 'Costa Rica',       'América'),
  ('1635', 'CU', 'Cuba',             'América'),
  ('2240', 'SV', 'El Salvador',      'América'),
  ('3093', 'GT', 'Guatemala',        'América'),
  ('3166', 'HT', 'Haiti',            'América'),
  ('3255', 'HN', 'Honduras',         'América'),
  ('4235', 'NI', 'Nicarágua',        'América'),
  ('5045', 'PA', 'Panamá',           'América'),
  ('2100', 'DO', 'República Dominicana', 'América'),
  ('3370', 'JM', 'Jamaica',          'América'),
  ('6253', 'TT', 'Trinidad e Tobago', 'América'),
  ('0884', 'BB', 'Barbados',         'América'),
  ('0833', 'BS', 'Bahamas',          'América'),
  ('0558', 'AG', 'Antígua e Barbuda', 'América'),
  ('0310', 'BZ', 'Belize',           'América'),

  -- ─── Europa Ocidental ────────────────────────────
  ('0370', 'DE', 'Alemanha',         'Europa'),
  ('0760', 'AT', 'Áustria',          'Europa'),
  ('0930', 'BE', 'Bélgica',          'Europa'),
  ('2534', 'FR', 'França',           'Europa'),
  ('3450', 'IT', 'Itália',           'Europa'),
  ('5754', 'GB', 'Reino Unido',      'Europa'),
  ('2453', 'ES', 'Espanha',          'Europa'),
  ('7560', 'PT', 'Portugal',         'Europa'),
  ('4995', 'NO', 'Noruega',          'Europa'),
  ('6289', 'SE', 'Suécia',           'Europa'),
  ('6408', 'CH', 'Suíça',            'Europa'),
  ('4065', 'LU', 'Luxemburgo',       'Europa'),
  ('4060', 'IE', 'Irlanda',          'Europa'),
  ('3514', 'IS', 'Islândia',         'Europa'),
  ('4766', 'NL', 'Países Baixos',    'Europa'),
  ('1449', 'DK', 'Dinamarca',        'Europa'),
  ('2464', 'FI', 'Finlândia',        'Europa'),
  ('2828', 'GR', 'Grécia',           'Europa'),

  -- ─── Europa Oriental / Central ───────────────────
  ('6238', 'RU', 'Rússia',           'Europa'),
  ('0795', 'BY', 'Bielorrússia',     'Europa'),
  ('7081', 'UA', 'Ucrânia',          'Europa'),
  ('5685', 'PL', 'Polônia',          'Europa'),
  ('1090', 'CZ', 'República Tcheca', 'Europa'),
  ('5461', 'SK', 'Eslováquia',       'Europa'),
  ('3220', 'HU', 'Hungria',          'Europa'),
  ('0272', 'AL', 'Albânia',          'Europa'),
  ('0639', 'BG', 'Bulgária',         'Europa'),
  ('5640', 'RO', 'Romênia',          'Europa'),
  ('2372', 'EE', 'Estônia',          'Europa'),
  ('3638', 'LV', 'Letônia',          'Europa'),
  ('3808', 'LT', 'Lituânia',         'Europa'),
  ('0892', 'BA', 'Bósnia e Herzegovina', 'Europa'),
  ('4430', 'MK', 'Macedônia do Norte', 'Europa'),
  ('4456', 'MD', 'Moldávia',         'Europa'),
  ('5908', 'RS', 'Sérvia',           'Europa'),
  ('1590', 'HR', 'Croácia',          'Europa'),
  ('4645', 'ME', 'Montenegro',       'Europa'),
  ('2135', 'SI', 'Eslovênia',        'Europa'),

  -- ─── Ásia Oriental e Sudeste Asiático ────────────
  ('1768', 'CN', 'China',            'Ásia'),
  ('4111', 'JP', 'Japão',            'Ásia'),
  ('1872', 'KR', 'Coreia do Sul',    'Ásia'),
  ('6599', 'TW', 'Taiwan',           'Ásia'),
  ('3298', 'HK', 'Hong Kong',        'Ásia'),
  ('5781', 'SG', 'Singapura',        'Ásia'),
  ('3310', 'ID', 'Indonésia',        'Ásia'),
  ('4383', 'MY', 'Malásia',          'Ásia'),
  ('5258', 'PH', 'Filipinas',        'Ásia'),
  ('6647', 'TH', 'Tailândia',        'Ásia'),
  ('7235', 'VN', 'Vietnã',           'Ásia'),
  ('0955', 'MM', 'Myanmar (Birmânia)', 'Ásia'),
  ('3557', 'KH', 'Camboja',          'Ásia'),
  ('3620', 'KP', 'Coreia do Norte',  'Ásia'),

  -- ─── Ásia do Sul e Central ────────────────────────
  ('3336', 'IN', 'Índia',            'Ásia'),
  ('5279', 'PK', 'Paquistão',        'Ásia'),
  ('0868', 'BD', 'Bangladesh',       'Ásia'),
  ('4758', 'NP', 'Nepal',            'Ásia'),
  ('0995', 'LK', 'Sri Lanka',        'Ásia'),
  ('0302', 'AF', 'Afeganistão',      'Ásia'),
  ('3417', 'IR', 'Irã',              'Ásia'),
  ('3425', 'IQ', 'Iraque',           'Ásia'),
  ('3433', 'IL', 'Israel',           'Ásia'),
  ('3484', 'JO', 'Jordânia',         'Ásia'),
  ('3611', 'KW', 'Kuwait',           'Ásia'),
  ('3646', 'LB', 'Líbano',           'Ásia'),
  ('5355', 'SA', 'Arábia Saudita',   'Ásia'),
  ('7358', 'AE', 'Emirados Árabes Unidos', 'Ásia'),
  ('6750', 'TR', 'Turquia',          'Ásia'),
  ('5070', 'OM', 'Omã',              'Ásia'),
  ('5584', 'QA', 'Catar',            'Ásia'),
  ('0817', 'BH', 'Barein',           'Ásia'),
  ('7300', 'YE', 'Iêmen',            'Ásia'),
  ('5525', 'SY', 'Síria',            'Ásia'),

  -- ─── África ──────────────────────────────────────
  ('0418', 'AO', 'Angola',           'África'),
  ('0426', 'DZ', 'Argélia',          'África'),
  ('4340', 'MA', 'Marrocos',         'África'),
  ('2402', 'EG', 'Egito',            'África'),
  ('0175', 'ZA', 'África do Sul',    'África'),
  ('4480', 'NG', 'Nigéria',          'África'),
  ('2542', 'ET', 'Etiópia',          'África'),
  ('3077', 'GH', 'Gana',             'África'),
  ('3549', 'CI', 'Costa do Marfim',  'África'),
  ('3379', 'KE', 'Quênia',           'África'),
  ('6158', 'TZ', 'Tanzânia',         'África'),
  ('6301', 'SD', 'Sudão',            'África'),
  ('1279', 'CM', 'Camarões',         'África'),
  ('2700', 'MZ', 'Moçambique',       'África'),
  ('4103', 'MG', 'Madagascar',       'África'),
  ('2763', 'GA', 'Gabão',            'África'),
  ('5509', 'SN', 'Senegal',          'África'),
  ('3076', 'GN', 'Guiné',            'África'),
  ('3107', 'GW', 'Guiné-Bissau',     'África'),
  ('5819', 'ST', 'São Tomé e Príncipe', 'África'),
  ('1198', 'CV', 'Cabo Verde',       'África'),
  ('3980', 'LY', 'Líbia',            'África'),
  ('7390', 'ZW', 'Zimbábue',         'África'),
  ('7285', 'ZM', 'Zâmbia',           'África'),

  -- ─── Oceania ─────────────────────────────────────
  ('0698', 'AU', 'Austrália',        'Oceania'),
  ('5053', 'NZ', 'Nova Zelândia',    'Oceania'),
  ('5177', 'PG', 'Papua Nova Guiné', 'Oceania'),
  ('2375', 'FJ', 'Fiji',             'Oceania'),
  ('5495', 'WS', 'Samoa',            'Oceania'),
  ('6506', 'TO', 'Tonga',            'Oceania'),
  ('7340', 'VU', 'Vanuatu',          'Oceania'),
  ('5060', 'NC', 'Nova Caledônia',   'Oceania'),
  ('5282', 'PF', 'Polinésia Francesa', 'Oceania'),
  ('5532', 'SB', 'Ilhas Salomão',    'Oceania'),
  ('4558', 'MH', 'Ilhas Marshall',   'Oceania'),
  ('4422', 'FM', 'Micronésia',       'Oceania'),
  ('5028', 'NR', 'Nauru',            'Oceania'),
  ('5746', 'KI', 'Quiribati',        'Oceania'),
  ('6743', 'TV', 'Tuvalu',           'Oceania')
ON CONFLICT (bacen) DO NOTHING;

-- Total de registros: 142
-- Códigos BACEN únicos: 142
-- Duplicatas corrigidas: 32 (em 2026-05-27)
